MMU_MEM_CTRL = $0000
MMU_IO_CTRL  = $0001
CLUT_IO = $0001
CLUT_0_ADDR = $D000
CLUT_1_ADDR = $D400
CLUT_2_ADDR = $D800
CLUT_3_ADDR = $DC00

MMU_BANK_0_REG = $08
MMU_BANK_1_REG = $09
MMU_BANK_2_REG = $0A
MMU_BANK_3_REG = $0B
MMU_BANK_4_REG = $0C
MMU_BANK_5_REG = $0D
MMU_BANK_6_REG = $0E
MMU_BANK_7_REG = $0F
MMU_MLUT_TABLE = $08

;Registers
VCKY_CTRL = $D000
VCKY_CTRL_ATTRIB = $D001
VCKY_LAYER_01_00_CTRL = $D002
VCKY_LAYER_02_CTRL = $D003
VKY_BKG_COL_B = $D00D ; Vicky Graphics Background Color Blue
VKY_BKG_COL_G = $D00E ; Vicky Graphics Background Color Green
VKY_BKG_COL_R = $D00F
VKY_BRDR_CTRL = $D004
FOREGROUND_COLOR = $D800
BACKGROUND_COLOR = $D840

POINTER_FILE = $CE
POINTER_MMU = $BC
POINTER_TXT = $A0
POINTER_SPR = $A2
POINTER_SPR_X = $A4
POINTER_SPR_Y = $A6
POINTER_SRC = $A6
POINTER_DST = $A8
POINTER_SCROLL_X = $A0
POINTER_SCROLL_Y = $A2
POINTER_CLUT_SRC = $A4
POINTER_CLUT_DEST = $A6
POINTER_UTIL = $A8
POINTER_TILE = $B0
POINTER_SET = $B2
POINTER_BMP = $B4
pointer = $B6
POINTER_PSG = $B8
POINTER_FRAME = $C0

POINTER_JMP = $C2
POINTER_STATUS = $C4
POINTER_MOVE = $C6
POINTER_INIT = $C8



SPRITE_SIZE = 16*16
SPRITE_START = mSpriteData
SPRITE_LETTERS = mSpriteData
SPRITE_NUMBERS = SPRITE_LETTERS  + (26 * SPRITE_SIZE)

BITMAP_START = mBitmapData
